import type { StationPoi } from "@/config/game";

export const STATION_POIS = [
  {
    id: "station-akabane",
    label: "Akabane",
    category: "station",
    emoji: "🚉",
    longitude: 139.7208,
    latitude: 35.778139,
    regionId: "akabane",
    unlocksRegionId: "akabane",
    lines: ["saikyo", "keihin-tohoku"],
  },
  {
    id: "station-akabane-iwabuchi",
    label: "Akabane-Iwabuchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.7221,
    latitude: 35.783448,
    regionId: "akabane-iwabuchi",
    unlocksRegionId: "akabane-iwabuchi",
    lines: ["namboku"],
  },
  {
    id: "station-akasaka-mitsuke",
    label: "Akasaka-Mitsuke",
    category: "station",
    emoji: "🚉",
    longitude: 139.736898,
    latitude: 35.675454,
    regionId: "akasaka-mitsuke",
    unlocksRegionId: "akasaka-mitsuke",
    lines: ["marunouchi", "ginza"],
  },
  {
    id: "station-akihabara",
    label: "Akihabara",
    category: "station",
    emoji: "🚉",
    longitude: 139.774309,
    latitude: 35.698551,
    regionId: "akihabara",
    unlocksRegionId: "akihabara",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-aobadai",
    label: "Aobadai",
    category: "station",
    emoji: "🚉",
    longitude: 139.517231,
    latitude: 35.542878,
    regionId: "aobadai",
    unlocksRegionId: "aobadai",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-aoyama-itchome",
    label: "Aoyama-Itchome",
    category: "station",
    emoji: "🚉",
    longitude: 139.723828,
    latitude: 35.672674,
    regionId: "aoyama-itchome",
    unlocksRegionId: "aoyama-itchome",
    lines: ["ginza"],
  },
  {
    id: "station-asagaya",
    label: "Asagaya",
    category: "station",
    emoji: "🚉",
    longitude: 139.635701,
    latitude: 35.705293,
    regionId: "asagaya",
    unlocksRegionId: "asagaya",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-asakusa",
    label: "Asakusa",
    category: "station",
    emoji: "🚉",
    longitude: 139.796691,
    latitude: 35.710755,
    regionId: "asakusa",
    unlocksRegionId: "asakusa",
    lines: ["ginza"],
  },
  {
    id: "station-atsugi",
    label: "Atsugi",
    category: "station",
    emoji: "🚉",
    longitude: 139.365112,
    latitude: 35.442905,
    regionId: "atsugi",
    unlocksRegionId: "atsugi",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-awajicho",
    label: "Awajicho",
    category: "station",
    emoji: "🚉",
    longitude: 139.768154,
    latitude: 35.696852,
    regionId: "awajicho",
    unlocksRegionId: "awajicho",
    lines: ["marunouchi"],
  },
  {
    id: "station-azabu-juban",
    label: "Azabu-Juban",
    category: "station",
    emoji: "🚉",
    longitude: 139.736656,
    latitude: 35.65584,
    regionId: "azabu-juban",
    unlocksRegionId: "azabu-juban",
    lines: ["namboku"],
  },
  {
    id: "station-azamino",
    label: "Azamino",
    category: "station",
    emoji: "🚉",
    longitude: 139.553521,
    latitude: 35.568362,
    regionId: "azamino",
    unlocksRegionId: "azamino",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-chitose-funabashi",
    label: "Chitose-Funabashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.633193,
    latitude: 35.647256,
    regionId: "chitose-funabashi",
    unlocksRegionId: "chitose-funabashi",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-chogo",
    label: "Chogo",
    category: "station",
    emoji: "🚉",
    longitude: 139.447124,
    latitude: 35.385876,
    regionId: "chogo",
    unlocksRegionId: "chogo",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-chuo-rinkan",
    label: "Chuo-Rinkan",
    category: "station",
    emoji: "🚉",
    longitude: 139.444356,
    latitude: 35.507551,
    regionId: "chuo-rinkan",
    unlocksRegionId: "chuo-rinkan",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-ebina",
    label: "Ebina",
    category: "station",
    emoji: "🚉",
    longitude: 139.390452,
    latitude: 35.445814,
    regionId: "ebina",
    unlocksRegionId: "ebina",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-ebisu",
    label: "Ebisu",
    category: "station",
    emoji: "🚉",
    longitude: 139.709427,
    latitude: 35.646708,
    regionId: "ebisu",
    unlocksRegionId: "ebisu",
    lines: ["yamanote", "saikyo"],
  },
  {
    id: "station-eda",
    label: "Eda",
    category: "station",
    emoji: "🚉",
    longitude: 139.551454,
    latitude: 35.558575,
    regionId: "eda",
    unlocksRegionId: "eda",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-enoshima",
    label: "Enoshima",
    category: "station",
    emoji: "🚉",
    longitude: 139.486452,
    latitude: 35.303118,
    regionId: "enoshima-station",
    unlocksRegionId: "enoshima-station",
    lines: ["enoden"],
  },
  {
    id: "station-fujigaoka",
    label: "Fujigaoka",
    category: "station",
    emoji: "🚉",
    longitude: 139.527979,
    latitude: 35.543498,
    regionId: "fujigaoka",
    unlocksRegionId: "fujigaoka",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-fujisawa",
    label: "Fujisawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.487245,
    latitude: 35.339314,
    regionId: "fujisawa",
    unlocksRegionId: "fujisawa",
    lines: ["odakyu-odawara", "enoden"],
  },
  {
    id: "station-fujisawa-hommachi",
    label: "Fujisawa-Hommachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.483927,
    latitude: 35.343216,
    regionId: "fujisawa-hommachi",
    unlocksRegionId: "fujisawa-hommachi",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-futako-shinchi",
    label: "Futako-Shinchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.622446,
    latitude: 35.607197,
    regionId: "futako-shinchi",
    unlocksRegionId: "futako-shinchi",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-futako-tamagawa",
    label: "Futako-Tamagawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.6268,
    latitude: 35.61179,
    regionId: "futako-tamagawa",
    unlocksRegionId: "futako-tamagawa",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-gaiemmae",
    label: "Gaiemmae",
    category: "station",
    emoji: "🚉",
    longitude: 139.717321,
    latitude: 35.671127,
    regionId: "gaiemmae",
    unlocksRegionId: "gaiemmae",
    lines: ["ginza"],
  },
  {
    id: "station-ginza",
    label: "Ginza",
    category: "station",
    emoji: "🚉",
    longitude: 139.766515,
    latitude: 35.671717,
    regionId: "ginza",
    unlocksRegionId: "ginza",
    lines: ["marunouchi", "ginza"],
  },
  {
    id: "station-gokurakuji",
    label: "Gokurakuji",
    category: "station",
    emoji: "🚉",
    longitude: 139.540752,
    latitude: 35.309714,
    regionId: "gokurakuji",
    unlocksRegionId: "gokurakuji",
    lines: ["enoden"],
  },
  {
    id: "station-gotanda",
    label: "Gotanda",
    category: "station",
    emoji: "🚉",
    longitude: 139.723995,
    latitude: 35.626161,
    regionId: "gotanda",
    unlocksRegionId: "gotanda",
    lines: ["yamanote"],
  },
  {
    id: "station-gotokuji",
    label: "Gotokuji",
    category: "station",
    emoji: "🚉",
    longitude: 139.646574,
    latitude: 35.649136,
    regionId: "gotokuji",
    unlocksRegionId: "gotokuji",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-hachioji",
    label: "Hachioji",
    category: "station",
    emoji: "🚉",
    longitude: 139.338916,
    latitude: 35.655523,
    regionId: "hachioji",
    unlocksRegionId: "hachioji",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-hadano",
    label: "Hadano",
    category: "station",
    emoji: "🚉",
    longitude: 139.222793,
    latitude: 35.365091,
    regionId: "hadano",
    unlocksRegionId: "hadano",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-hamamatsucho",
    label: "Hamamatsucho",
    category: "station",
    emoji: "🚉",
    longitude: 139.757062,
    latitude: 35.655111,
    regionId: "hamamatsucho",
    unlocksRegionId: "hamamatsucho",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-harajuku",
    label: "Harajuku",
    category: "station",
    emoji: "🚉",
    longitude: 139.702427,
    latitude: 35.670215,
    regionId: "harajuku",
    unlocksRegionId: "harajuku",
    lines: ["yamanote"],
  },
  {
    id: "station-hase",
    label: "Hase",
    category: "station",
    emoji: "🚉",
    longitude: 139.548211,
    latitude: 35.315082,
    regionId: "hase",
    unlocksRegionId: "hase",
    lines: ["enoden"],
  },
  {
    id: "station-higashi-jujo",
    label: "Higashi-Jujo",
    category: "station",
    emoji: "🚉",
    longitude: 139.726875,
    latitude: 35.763848,
    regionId: "higashi-jujo",
    unlocksRegionId: "higashi-jujo",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-higashi-kanagawa",
    label: "Higashi-Kanagawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.633327,
    latitude: 35.477943,
    regionId: "higashi-kanagawa",
    unlocksRegionId: "higashi-kanagawa",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-higashi-kitazawa",
    label: "Higashi-Kitazawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.669301,
    latitude: 35.665188,
    regionId: "higashi-kitazawa",
    unlocksRegionId: "higashi-kitazawa",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-higashi-koenji",
    label: "Higashi-Koenji",
    category: "station",
    emoji: "🚉",
    longitude: 139.660512,
    latitude: 35.702014,
    regionId: "higashi-koenji",
    unlocksRegionId: "higashi-koenji",
    lines: ["marunouchi"],
  },
  {
    id: "station-higashi-koganei",
    label: "Higashi-Koganei",
    category: "station",
    emoji: "🚉",
    longitude: 139.521341,
    latitude: 35.702356,
    regionId: "higashi-koganei",
    unlocksRegionId: "higashi-koganei",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-higashi-rinkan",
    label: "Higashi-Rinkan",
    category: "station",
    emoji: "🚉",
    longitude: 139.442361,
    latitude: 35.522971,
    regionId: "higashi-rinkan",
    unlocksRegionId: "higashi-rinkan",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-hino",
    label: "Hino",
    category: "station",
    emoji: "🚉",
    longitude: 139.396033,
    latitude: 35.677284,
    regionId: "hino",
    unlocksRegionId: "hino",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-hon-atsugi",
    label: "Hon-Atsugi",
    category: "station",
    emoji: "🚉",
    longitude: 139.363208,
    latitude: 35.436738,
    regionId: "hon-atsugi",
    unlocksRegionId: "hon-atsugi",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-hon-komagome",
    label: "Hon-Komagome",
    category: "station",
    emoji: "🚉",
    longitude: 139.753701,
    latitude: 35.724763,
    regionId: "hon-komagome",
    unlocksRegionId: "hon-komagome",
    lines: ["namboku"],
  },
  {
    id: "station-honancho",
    label: "Honancho",
    category: "station",
    emoji: "🚉",
    longitude: 139.657023,
    latitude: 35.680158,
    regionId: "honancho",
    unlocksRegionId: "honancho",
    lines: ["marunouchi"],
  },
  {
    id: "station-hongo-sanchome",
    label: "Hongo-Sanchome",
    category: "station",
    emoji: "🚉",
    longitude: 139.759118,
    latitude: 35.707724,
    regionId: "hongo-sanchome",
    unlocksRegionId: "hongo-sanchome",
    lines: ["marunouchi"],
  },
  {
    id: "station-honkugenuma",
    label: "Honkugenuma",
    category: "station",
    emoji: "🚉",
    longitude: 139.487214,
    latitude: 35.321815,
    regionId: "honkugenuma",
    unlocksRegionId: "honkugenuma",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-ichigao",
    label: "Ichigao",
    category: "station",
    emoji: "🚉",
    longitude: 139.541281,
    latitude: 35.551348,
    regionId: "ichigao",
    unlocksRegionId: "ichigao",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-ichigaya",
    label: "Ichigaya",
    category: "station",
    emoji: "🚉",
    longitude: 139.736659,
    latitude: 35.692079,
    regionId: "ichigaya",
    unlocksRegionId: "ichigaya",
    lines: ["namboku"],
  },
  {
    id: "station-iidabashi",
    label: "Iidabashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.744835,
    latitude: 35.701782,
    regionId: "iidabashi",
    unlocksRegionId: "iidabashi",
    lines: ["namboku"],
  },
  {
    id: "station-ikebukuro",
    label: "Ikebukuro",
    category: "station",
    emoji: "🚉",
    longitude: 139.710508,
    latitude: 35.729955,
    regionId: "ikebukuro",
    unlocksRegionId: "ikebukuro",
    lines: ["yamanote", "saikyo", "marunouchi"],
  },
  {
    id: "station-ikejiri-ohashi",
    label: "Ikejiri-Ohashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.684772,
    latitude: 35.650763,
    regionId: "ikejiri-ohashi",
    unlocksRegionId: "ikejiri-ohashi",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-ikuta",
    label: "Ikuta",
    category: "station",
    emoji: "🚉",
    longitude: 139.567201,
    latitude: 35.617382,
    regionId: "ikuta",
    unlocksRegionId: "ikuta",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-inamuragasaki",
    label: "Inamuragasaki",
    category: "station",
    emoji: "🚉",
    longitude: 139.531224,
    latitude: 35.305872,
    regionId: "inamuragasaki",
    unlocksRegionId: "inamuragasaki",
    lines: ["enoden"],
  },
  {
    id: "station-inaricho",
    label: "Inaricho",
    category: "station",
    emoji: "🚉",
    longitude: 139.781241,
    latitude: 35.711792,
    regionId: "inaricho",
    unlocksRegionId: "inaricho",
    lines: ["ginza"],
  },
  {
    id: "station-isehara",
    label: "Isehara",
    category: "station",
    emoji: "🚉",
    longitude: 139.301226,
    latitude: 35.401156,
    regionId: "isehara",
    unlocksRegionId: "isehara",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-ishigami",
    label: "Ishigami",
    category: "station",
    emoji: "🚉",
    longitude: 139.487121,
    latitude: 35.335372,
    regionId: "ishigami",
    unlocksRegionId: "ishigami",
    lines: ["enoden"],
  },
  {
    id: "station-ishikawacho",
    label: "Ishikawacho",
    category: "station",
    emoji: "🚉",
    longitude: 139.642747,
    latitude: 35.439226,
    regionId: "ishikawacho",
    unlocksRegionId: "ishikawacho",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-isogo",
    label: "Isogo",
    category: "station",
    emoji: "🚉",
    longitude: 139.618158,
    latitude: 35.400137,
    regionId: "isogo",
    unlocksRegionId: "isogo",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-itabashi",
    label: "Itabashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.719437,
    latitude: 35.745272,
    regionId: "itabashi",
    unlocksRegionId: "itabashi",
    lines: ["saikyo"],
  },
  {
    id: "station-izumi-tamagawa",
    label: "Izumi-Tamagawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.578117,
    latitude: 35.632412,
    regionId: "izumi-tamagawa",
    unlocksRegionId: "izumi-tamagawa",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-jujo",
    label: "Jujo",
    category: "station",
    emoji: "🚉",
    longitude: 139.722307,
    latitude: 35.760008,
    regionId: "jujo",
    unlocksRegionId: "jujo",
    lines: ["saikyo"],
  },
  {
    id: "station-kaisei",
    label: "Kaisei",
    category: "station",
    emoji: "🚉",
    longitude: 139.144427,
    latitude: 35.323685,
    regionId: "kaisei",
    unlocksRegionId: "kaisei",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-kajigaya",
    label: "Kajigaya",
    category: "station",
    emoji: "🚉",
    longitude: 139.605479,
    latitude: 35.593651,
    regionId: "kajigaya",
    unlocksRegionId: "kajigaya",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-kakio",
    label: "Kakio",
    category: "station",
    emoji: "🚉",
    longitude: 139.513928,
    latitude: 35.605727,
    regionId: "kakio",
    unlocksRegionId: "kakio",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-kamakura",
    label: "Kamakura",
    category: "station",
    emoji: "🚉",
    longitude: 139.550204,
    latitude: 35.319372,
    regionId: "kamakura",
    unlocksRegionId: "kamakura",
    lines: ["enoden"],
  },
  {
    id: "station-kamakura-koko-mae",
    label: "Kamakura-Koko-Mae",
    category: "station",
    emoji: "🚉",
    longitude: 139.499103,
    latitude: 35.301245,
    regionId: "kamakura-koko-mae",
    unlocksRegionId: "kamakura-koko-mae",
    lines: ["enoden"],
  },
  {
    id: "station-kamata",
    label: "Kamata",
    category: "station",
    emoji: "🚉",
    longitude: 139.715272,
    latitude: 35.561884,
    regionId: "kamata",
    unlocksRegionId: "kamata",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kami-nakazato",
    label: "Kami-Nakazato",
    category: "station",
    emoji: "🚉",
    longitude: 139.74698,
    latitude: 35.746579,
    regionId: "kami-nakazato",
    unlocksRegionId: "kami-nakazato",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kanda",
    label: "Kanda",
    category: "station",
    emoji: "🚉",
    longitude: 139.7709,
    latitude: 35.692754,
    regionId: "kanda",
    unlocksRegionId: "kanda",
    lines: ["yamanote", "keihin-tohoku", "chuo-rapid", "ginza"],
  },
  {
    id: "station-kannai",
    label: "Kannai",
    category: "station",
    emoji: "🚉",
    longitude: 139.63637,
    latitude: 35.444706,
    regionId: "kannai",
    unlocksRegionId: "kannai",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kasumigaseki",
    label: "Kasumigaseki",
    category: "station",
    emoji: "🚉",
    longitude: 139.751347,
    latitude: 35.673712,
    regionId: "kasumigaseki",
    unlocksRegionId: "kasumigaseki",
    lines: ["marunouchi"],
  },
  {
    id: "station-katase-enoshima",
    label: "Katase-Enoshima",
    category: "station",
    emoji: "🚉",
    longitude: 139.485217,
    latitude: 35.302011,
    regionId: "katase-enoshima",
    unlocksRegionId: "katase-enoshima",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-kawaguchi",
    label: "Kawaguchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.717512,
    latitude: 35.801926,
    regionId: "kawaguchi",
    unlocksRegionId: "kawaguchi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kawasaki",
    label: "Kawasaki",
    category: "station",
    emoji: "🚉",
    longitude: 139.696893,
    latitude: 35.531404,
    regionId: "kawasaki",
    unlocksRegionId: "kawasaki",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kichijoji",
    label: "Kichijoji",
    category: "station",
    emoji: "🚉",
    longitude: 139.579814,
    latitude: 35.703137,
    regionId: "kichijoji",
    unlocksRegionId: "kichijoji",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-kita-akabane",
    label: "Kita-Akabane",
    category: "station",
    emoji: "🚉",
    longitude: 139.706029,
    latitude: 35.786781,
    regionId: "kita-akabane",
    unlocksRegionId: "kita-akabane",
    lines: ["saikyo"],
  },
  {
    id: "station-kita-toda",
    label: "Kita-Toda",
    category: "station",
    emoji: "🚉",
    longitude: 139.660111,
    latitude: 35.827653,
    regionId: "kita-toda",
    unlocksRegionId: "kita-toda",
    lines: ["saikyo"],
  },
  {
    id: "station-kita-urawa",
    label: "Kita-Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.646106,
    latitude: 35.872155,
    regionId: "kita-urawa",
    unlocksRegionId: "kita-urawa",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kita-yono",
    label: "Kita-Yono",
    category: "station",
    emoji: "🚉",
    longitude: 139.628505,
    latitude: 35.890498,
    regionId: "kita-yono",
    unlocksRegionId: "kita-yono",
    lines: ["saikyo"],
  },
  {
    id: "station-kitami",
    label: "Kitami",
    category: "station",
    emoji: "🚉",
    longitude: 139.585224,
    latitude: 35.635817,
    regionId: "kitami",
    unlocksRegionId: "kitami",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-koenji",
    label: "Koenji",
    category: "station",
    emoji: "🚉",
    longitude: 139.649418,
    latitude: 35.705128,
    regionId: "koenji",
    unlocksRegionId: "koenji",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-kokkai-gijidomae",
    label: "Kokkai-Gijidomae",
    category: "station",
    emoji: "🚉",
    longitude: 139.744322,
    latitude: 35.674921,
    regionId: "kokkai-gijidomae",
    unlocksRegionId: "kokkai-gijidomae",
    lines: ["marunouchi"],
  },
  {
    id: "station-kokubunji",
    label: "Kokubunji",
    category: "station",
    emoji: "🚉",
    longitude: 139.479512,
    latitude: 35.700078,
    regionId: "kokubunji",
    unlocksRegionId: "kokubunji",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-komae",
    label: "Komae",
    category: "station",
    emoji: "🚉",
    longitude: 139.575024,
    latitude: 35.634828,
    regionId: "komae",
    unlocksRegionId: "komae",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-komagome",
    label: "Komagome",
    category: "station",
    emoji: "🚉",
    longitude: 139.747001,
    latitude: 35.736286,
    regionId: "komagome",
    unlocksRegionId: "komagome",
    lines: ["yamanote", "namboku"],
  },
  {
    id: "station-komazawa-daigaku",
    label: "Komazawa-Daigaku",
    category: "station",
    emoji: "🚉",
    longitude: 139.661156,
    latitude: 35.633193,
    regionId: "komazawa-daigaku",
    unlocksRegionId: "komazawa-daigaku",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-konandai",
    label: "Konandai",
    category: "station",
    emoji: "🚉",
    longitude: 139.576696,
    latitude: 35.375295,
    regionId: "konandai",
    unlocksRegionId: "konandai",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-korakuen",
    label: "Korakuen",
    category: "station",
    emoji: "🚉",
    longitude: 139.751507,
    latitude: 35.707801,
    regionId: "korakuen",
    unlocksRegionId: "korakuen",
    lines: ["namboku", "marunouchi"],
  },
  {
    id: "station-koshigoe",
    label: "Koshigoe",
    category: "station",
    emoji: "🚉",
    longitude: 139.492107,
    latitude: 35.303287,
    regionId: "koshigoe",
    unlocksRegionId: "koshigoe",
    lines: ["enoden"],
  },
  {
    id: "station-kozashibuya",
    label: "Kozashibuya",
    category: "station",
    emoji: "🚉",
    longitude: 139.464321,
    latitude: 35.371058,
    regionId: "kozashibuya",
    unlocksRegionId: "kozashibuya",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-kugenuma",
    label: "Kugenuma",
    category: "station",
    emoji: "🚉",
    longitude: 139.490218,
    latitude: 35.322047,
    regionId: "kugenuma",
    unlocksRegionId: "kugenuma",
    lines: ["enoden"],
  },
  {
    id: "station-kunitachi",
    label: "Kunitachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.443217,
    latitude: 35.697917,
    regionId: "kunitachi",
    unlocksRegionId: "kunitachi",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-kyobashi",
    label: "Kyobashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.770515,
    latitude: 35.676819,
    regionId: "kyobashi",
    unlocksRegionId: "kyobashi",
    lines: ["ginza"],
  },
  {
    id: "station-kyodo",
    label: "Kyodo",
    category: "station",
    emoji: "🚉",
    longitude: 139.640124,
    latitude: 35.653022,
    regionId: "kyodo",
    unlocksRegionId: "kyodo",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-machida",
    label: "Machida",
    category: "station",
    emoji: "🚉",
    longitude: 139.446787,
    latitude: 35.542021,
    regionId: "machida",
    unlocksRegionId: "machida",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-meguro",
    label: "Meguro",
    category: "station",
    emoji: "🚉",
    longitude: 139.715752,
    latitude: 35.633287,
    regionId: "meguro",
    unlocksRegionId: "meguro",
    lines: ["yamanote", "namboku"],
  },
  {
    id: "station-mejiro",
    label: "Mejiro",
    category: "station",
    emoji: "🚉",
    longitude: 139.706465,
    latitude: 35.721192,
    regionId: "mejiro",
    unlocksRegionId: "mejiro",
    lines: ["yamanote"],
  },
  {
    id: "station-minami-asagaya",
    label: "Minami-Asagaya",
    category: "station",
    emoji: "🚉",
    longitude: 139.640317,
    latitude: 35.698711,
    regionId: "minami-asagaya",
    unlocksRegionId: "minami-asagaya",
    lines: ["marunouchi"],
  },
  {
    id: "station-minami-machida-grandberry-park",
    label: "Minami-Machida Grandberry Park",
    category: "station",
    emoji: "🚉",
    longitude: 139.470791,
    latitude: 35.511501,
    regionId: "minami-machida-grandberry-park",
    unlocksRegionId: "minami-machida-grandberry-park",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-minami-shinjuku",
    label: "Minami-Shinjuku",
    category: "station",
    emoji: "🚉",
    longitude: 139.699127,
    latitude: 35.687324,
    regionId: "minami-shinjuku",
    unlocksRegionId: "minami-shinjuku",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-minami-urawa",
    label: "Minami-Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.669144,
    latitude: 35.847732,
    regionId: "minami-urawa",
    unlocksRegionId: "minami-urawa",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-minami-yono",
    label: "Minami-Yono",
    category: "station",
    emoji: "🚉",
    longitude: 139.631039,
    latitude: 35.867886,
    regionId: "minami-yono",
    unlocksRegionId: "minami-yono",
    lines: ["saikyo"],
  },
  {
    id: "station-mitaka",
    label: "Mitaka",
    category: "station",
    emoji: "🚉",
    longitude: 139.560571,
    latitude: 35.702758,
    regionId: "mitaka",
    unlocksRegionId: "mitaka",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-mitsukoshimae",
    label: "Mitsukoshimae",
    category: "station",
    emoji: "🚉",
    longitude: 139.773621,
    latitude: 35.685183,
    regionId: "mitsukoshimae",
    unlocksRegionId: "mitsukoshimae",
    lines: ["ginza"],
  },
  {
    id: "station-miyamaedaira",
    label: "Miyamaedaira",
    category: "station",
    emoji: "🚉",
    longitude: 139.582039,
    latitude: 35.584962,
    regionId: "miyamaedaira",
    unlocksRegionId: "miyamaedaira",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-miyazakidai",
    label: "Miyazakidai",
    category: "station",
    emoji: "🚉",
    longitude: 139.591125,
    latitude: 35.587053,
    regionId: "miyazakidai",
    unlocksRegionId: "miyazakidai",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-mizonokuchi",
    label: "Mizonokuchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.610511,
    latitude: 35.599925,
    regionId: "mizonokuchi",
    unlocksRegionId: "mizonokuchi",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-mukogaoka-yuen",
    label: "Mukogaoka-Yuen",
    category: "station",
    emoji: "🚉",
    longitude: 139.560218,
    latitude: 35.615328,
    regionId: "mukogaoka-yuen",
    unlocksRegionId: "mukogaoka-yuen",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-musashi-koganei",
    label: "Musashi-Koganei",
    category: "station",
    emoji: "🚉",
    longitude: 139.515517,
    latitude: 35.701659,
    regionId: "musashi-koganei",
    unlocksRegionId: "musashi-koganei",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-musashi-sakai",
    label: "Musashi-Sakai",
    category: "station",
    emoji: "🚉",
    longitude: 139.546117,
    latitude: 35.702652,
    regionId: "musashi-sakai",
    unlocksRegionId: "musashi-sakai",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-musashi-urawa",
    label: "Musashi-Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.647066,
    latitude: 35.845969,
    regionId: "musashi-urawa",
    unlocksRegionId: "musashi-urawa",
    lines: ["saikyo"],
  },
  {
    id: "station-myogadani",
    label: "Myogadani",
    category: "station",
    emoji: "🚉",
    longitude: 139.740822,
    latitude: 35.715734,
    regionId: "myogadani",
    unlocksRegionId: "myogadani",
    lines: ["marunouchi"],
  },
  {
    id: "station-nagatacho",
    label: "Nagatacho",
    category: "station",
    emoji: "🚉",
    longitude: 139.739896,
    latitude: 35.67832,
    regionId: "nagatacho",
    unlocksRegionId: "nagatacho",
    lines: ["namboku"],
  },
  {
    id: "station-nagatsuta",
    label: "Nagatsuta",
    category: "station",
    emoji: "🚉",
    longitude: 139.49437,
    latitude: 35.531899,
    regionId: "nagatsuta",
    unlocksRegionId: "nagatsuta",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-naka-urawa",
    label: "Naka-Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.637722,
    latitude: 35.853525,
    regionId: "naka-urawa",
    unlocksRegionId: "naka-urawa",
    lines: ["saikyo"],
  },
  {
    id: "station-nakano",
    label: "Nakano",
    category: "station",
    emoji: "🚉",
    longitude: 139.665954,
    latitude: 35.706079,
    regionId: "nakano",
    unlocksRegionId: "nakano",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-nakano-fujimicho",
    label: "Nakano-Fujimicho",
    category: "station",
    emoji: "🚉",
    longitude: 139.657126,
    latitude: 35.687421,
    regionId: "nakano-fujimicho",
    unlocksRegionId: "nakano-fujimicho",
    lines: ["marunouchi"],
  },
  {
    id: "station-nakano-sakaue",
    label: "Nakano-Sakaue",
    category: "station",
    emoji: "🚉",
    longitude: 139.681482,
    latitude: 35.694326,
    regionId: "nakano-sakaue",
    unlocksRegionId: "nakano-sakaue",
    lines: ["marunouchi"],
  },
  {
    id: "station-nakano-shimbashi",
    label: "Nakano-Shimbashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.664218,
    latitude: 35.688412,
    regionId: "nakano-shimbashi",
    unlocksRegionId: "nakano-shimbashi",
    lines: ["marunouchi"],
  },
  {
    id: "station-negishi",
    label: "Negishi",
    category: "station",
    emoji: "🚉",
    longitude: 139.63505,
    latitude: 35.415657,
    regionId: "negishi",
    unlocksRegionId: "negishi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-nihombashi",
    label: "Nihombashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.774428,
    latitude: 35.682571,
    regionId: "nihombashi",
    unlocksRegionId: "nihombashi",
    lines: ["ginza"],
  },
  {
    id: "station-nippori",
    label: "Nippori",
    category: "station",
    emoji: "🚉",
    longitude: 139.771001,
    latitude: 35.728483,
    regionId: "nippori",
    unlocksRegionId: "nippori",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-nishi-hachioji",
    label: "Nishi-Hachioji",
    category: "station",
    emoji: "🚉",
    longitude: 139.316952,
    latitude: 35.653764,
    regionId: "nishi-hachioji",
    unlocksRegionId: "nishi-hachioji",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-nishi-kawaguchi",
    label: "Nishi-Kawaguchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.704482,
    latitude: 35.815583,
    regionId: "nishi-kawaguchi",
    unlocksRegionId: "nishi-kawaguchi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-nishi-kokubunji",
    label: "Nishi-Kokubunji",
    category: "station",
    emoji: "🚉",
    longitude: 139.461147,
    latitude: 35.698918,
    regionId: "nishi-kokubunji",
    unlocksRegionId: "nishi-kokubunji",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-nishi-nippori",
    label: "Nishi-Nippori",
    category: "station",
    emoji: "🚉",
    longitude: 139.767332,
    latitude: 35.73284,
    regionId: "nishi-nippori",
    unlocksRegionId: "nishi-nippori",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-nishi-ogikubo",
    label: "Nishi-Ogikubo",
    category: "station",
    emoji: "🚉",
    longitude: 139.599012,
    latitude: 35.703715,
    regionId: "nishi-ogikubo",
    unlocksRegionId: "nishi-ogikubo",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-nishi-shinjuku",
    label: "Nishi-Shinjuku",
    category: "station",
    emoji: "🚉",
    longitude: 139.692018,
    latitude: 35.694721,
    regionId: "nishi-shinjuku",
    unlocksRegionId: "nishi-shinjuku",
    lines: ["marunouchi"],
  },
  {
    id: "station-nishigahara",
    label: "Nishigahara",
    category: "station",
    emoji: "🚉",
    longitude: 139.742172,
    latitude: 35.74605,
    regionId: "nishigahara",
    unlocksRegionId: "nishigahara",
    lines: ["namboku"],
  },
  {
    id: "station-noborito",
    label: "Noborito",
    category: "station",
    emoji: "🚉",
    longitude: 139.557327,
    latitude: 35.621818,
    regionId: "noborito",
    unlocksRegionId: "noborito",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-ochanomizu",
    label: "Ochanomizu",
    category: "station",
    emoji: "🚉",
    longitude: 139.765434,
    latitude: 35.699463,
    regionId: "ochanomizu",
    unlocksRegionId: "ochanomizu",
    lines: ["chuo-rapid", "marunouchi"],
  },
  {
    id: "station-odakyu-sagamihara",
    label: "Odakyu-Sagamihara",
    category: "station",
    emoji: "🚉",
    longitude: 139.416112,
    latitude: 35.554321,
    regionId: "odakyu-sagamihara",
    unlocksRegionId: "odakyu-sagamihara",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-odawara",
    label: "Odawara",
    category: "station",
    emoji: "🚉",
    longitude: 139.156311,
    latitude: 35.256128,
    regionId: "odawara",
    unlocksRegionId: "odawara",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-ofuna",
    label: "Ofuna",
    category: "station",
    emoji: "🚉",
    longitude: 139.531394,
    latitude: 35.353348,
    regionId: "ofuna",
    unlocksRegionId: "ofuna",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-ogikubo",
    label: "Ogikubo",
    category: "station",
    emoji: "🚉",
    longitude: 139.620182,
    latitude: 35.704219,
    regionId: "ogikubo",
    unlocksRegionId: "ogikubo",
    lines: ["chuo-rapid", "marunouchi"],
  },
  {
    id: "station-oimachi",
    label: "Oimachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.73454,
    latitude: 35.607159,
    regionId: "oimachi",
    unlocksRegionId: "oimachi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-oji",
    label: "Oji",
    category: "station",
    emoji: "🚉",
    longitude: 139.7379,
    latitude: 35.753154,
    regionId: "oji",
    unlocksRegionId: "oji",
    lines: ["keihin-tohoku", "namboku"],
  },
  {
    id: "station-oji-kamiya",
    label: "Oji-Kamiya",
    category: "station",
    emoji: "🚉",
    longitude: 139.735718,
    latitude: 35.765055,
    regionId: "oji-kamiya",
    unlocksRegionId: "oji-kamiya",
    lines: ["namboku"],
  },
  {
    id: "station-okachimachi",
    label: "Okachimachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.77463,
    latitude: 35.706953,
    regionId: "okachimachi",
    unlocksRegionId: "okachimachi",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-omiya",
    label: "Omiya",
    category: "station",
    emoji: "🚉",
    longitude: 139.62347,
    latitude: 35.907133,
    regionId: "omiya",
    unlocksRegionId: "omiya",
    lines: ["saikyo", "keihin-tohoku"],
  },
  {
    id: "station-omori",
    label: "Omori",
    category: "station",
    emoji: "🚉",
    longitude: 139.727933,
    latitude: 35.588473,
    regionId: "omori",
    unlocksRegionId: "omori",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-omotesando",
    label: "Omotesando",
    category: "station",
    emoji: "🚉",
    longitude: 139.712637,
    latitude: 35.665328,
    regionId: "omotesando",
    unlocksRegionId: "omotesando",
    lines: ["ginza"],
  },
  {
    id: "station-osaki",
    label: "Osaki",
    category: "station",
    emoji: "🚉",
    longitude: 139.728487,
    latitude: 35.61939,
    regionId: "osaki",
    unlocksRegionId: "osaki",
    lines: ["yamanote", "saikyo"],
  },
  {
    id: "station-otemachi",
    label: "Otemachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.766472,
    latitude: 35.684533,
    regionId: "otemachi",
    unlocksRegionId: "otemachi",
    lines: ["marunouchi"],
  },
  {
    id: "station-otsuka",
    label: "Otsuka",
    category: "station",
    emoji: "🚉",
    longitude: 139.728588,
    latitude: 35.731685,
    regionId: "otsuka",
    unlocksRegionId: "otsuka",
    lines: ["yamanote"],
  },
  {
    id: "station-roppongi-itchome",
    label: "Roppongi-Itchome",
    category: "station",
    emoji: "🚉",
    longitude: 139.738849,
    latitude: 35.664973,
    regionId: "roppongi-itchome",
    unlocksRegionId: "roppongi-itchome",
    lines: ["namboku"],
  },
  {
    id: "station-sagami-ono",
    label: "Sagami-Ono",
    category: "station",
    emoji: "🚉",
    longitude: 139.446127,
    latitude: 35.531042,
    regionId: "sagami-ono",
    unlocksRegionId: "sagami-ono",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-saginuma",
    label: "Saginuma",
    category: "station",
    emoji: "🚉",
    longitude: 139.572855,
    latitude: 35.579444,
    regionId: "saginuma",
    unlocksRegionId: "saginuma",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-saitama-shintoshin",
    label: "Saitama-Shintoshin",
    category: "station",
    emoji: "🚉",
    longitude: 139.633948,
    latitude: 35.893637,
    regionId: "saitama-shintoshin",
    unlocksRegionId: "saitama-shintoshin",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-sakura-shinmachi",
    label: "Sakura-Shinmachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.645369,
    latitude: 35.631724,
    regionId: "sakura-shinmachi",
    unlocksRegionId: "sakura-shinmachi",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-sakuragicho",
    label: "Sakuragicho",
    category: "station",
    emoji: "🚉",
    longitude: 139.630894,
    latitude: 35.450316,
    regionId: "sakuragicho",
    unlocksRegionId: "sakuragicho",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-sangen-jaya",
    label: "Sangen-Jaya",
    category: "station",
    emoji: "🚉",
    longitude: 139.670186,
    latitude: 35.643806,
    regionId: "sangen-jaya",
    unlocksRegionId: "sangen-jaya",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-sangubashi",
    label: "Sangubashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.697128,
    latitude: 35.678224,
    regionId: "sangubashi",
    unlocksRegionId: "sangubashi",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-seijogakuen-mae",
    label: "Seijogakuen-mae",
    category: "station",
    emoji: "🚉",
    longitude: 139.601415,
    latitude: 35.640217,
    regionId: "seijogakuen-mae",
    unlocksRegionId: "seijogakuen-mae",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-setagaya-daita",
    label: "Setagaya-Daita",
    category: "station",
    emoji: "🚉",
    longitude: 139.657218,
    latitude: 35.660421,
    regionId: "setagaya-daita",
    unlocksRegionId: "setagaya-daita",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-shibusawa",
    label: "Shibusawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.191572,
    latitude: 35.372814,
    regionId: "shibusawa",
    unlocksRegionId: "shibusawa",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-shibuya",
    label: "Shibuya",
    category: "station",
    emoji: "🚉",
    longitude: 139.701637,
    latitude: 35.658713,
    regionId: "shibuya",
    unlocksRegionId: "shibuya",
    lines: ["yamanote", "saikyo", "den-en-toshi", "ginza"],
  },
  {
    id: "station-shichirigahama",
    label: "Shichirigahama",
    category: "station",
    emoji: "🚉",
    longitude: 139.516523,
    latitude: 35.306128,
    regionId: "shichirigahama",
    unlocksRegionId: "shichirigahama",
    lines: ["enoden"],
  },
  {
    id: "station-shimo",
    label: "Shimo",
    category: "station",
    emoji: "🚉",
    longitude: 139.732526,
    latitude: 35.777904,
    regionId: "shimo",
    unlocksRegionId: "shimo",
    lines: ["namboku"],
  },
  {
    id: "station-shimo-kitazawa",
    label: "Shimo-Kitazawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.667421,
    latitude: 35.662849,
    regionId: "shimo-kitazawa",
    unlocksRegionId: "shimo-kitazawa",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-shin-koenji",
    label: "Shin-Koenji",
    category: "station",
    emoji: "🚉",
    longitude: 139.654311,
    latitude: 35.702017,
    regionId: "shin-koenji",
    unlocksRegionId: "shin-koenji",
    lines: ["marunouchi"],
  },
  {
    id: "station-shin-koyasu",
    label: "Shin-Koyasu",
    category: "station",
    emoji: "🚉",
    longitude: 139.654164,
    latitude: 35.486875,
    regionId: "shin-koyasu",
    unlocksRegionId: "shin-koyasu",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-shin-matsuda",
    label: "Shin-Matsuda",
    category: "station",
    emoji: "🚉",
    longitude: 139.140427,
    latitude: 35.359218,
    regionId: "shin-matsuda",
    unlocksRegionId: "shin-matsuda",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-shin-nakano",
    label: "Shin-Nakano",
    category: "station",
    emoji: "🚉",
    longitude: 139.669327,
    latitude: 35.696421,
    regionId: "shin-nakano",
    unlocksRegionId: "shin-nakano",
    lines: ["marunouchi"],
  },
  {
    id: "station-shin-okubo",
    label: "Shin-Okubo",
    category: "station",
    emoji: "🚉",
    longitude: 139.700242,
    latitude: 35.701301,
    regionId: "shin-okubo",
    unlocksRegionId: "shin-okubo",
    lines: ["yamanote"],
  },
  {
    id: "station-shin-otsuka",
    label: "Shin-Otsuka",
    category: "station",
    emoji: "🚉",
    longitude: 139.729114,
    latitude: 35.729015,
    regionId: "shin-otsuka",
    unlocksRegionId: "shin-otsuka",
    lines: ["marunouchi"],
  },
  {
    id: "station-shin-sugita",
    label: "Shin-Sugita",
    category: "station",
    emoji: "🚉",
    longitude: 139.619992,
    latitude: 35.386278,
    regionId: "shin-sugita",
    unlocksRegionId: "shin-sugita",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-shin-yurigaoka",
    label: "Shin-Yurigaoka",
    category: "station",
    emoji: "🚉",
    longitude: 139.505221,
    latitude: 35.607327,
    regionId: "shin-yurigaoka",
    unlocksRegionId: "shin-yurigaoka",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-shinagawa",
    label: "Shinagawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.739068,
    latitude: 35.628449,
    regionId: "shinagawa",
    unlocksRegionId: "shinagawa",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-shinbashi",
    label: "Shinbashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.75909,
    latitude: 35.666027,
    regionId: "shinbashi",
    unlocksRegionId: "shinbashi",
    lines: ["yamanote", "keihin-tohoku", "ginza"],
  },
  {
    id: "station-shinjuku",
    label: "Shinjuku",
    category: "station",
    emoji: "🚉",
    longitude: 139.699785,
    latitude: 35.69033,
    regionId: "shinjuku",
    unlocksRegionId: "shinjuku",
    lines: ["yamanote", "saikyo", "chuo-rapid", "marunouchi", "odakyu-odawara"],
  },
  {
    id: "station-shinjuku-gyoemmae",
    label: "Shinjuku-Gyoemmae",
    category: "station",
    emoji: "🚉",
    longitude: 139.711327,
    latitude: 35.687514,
    regionId: "shinjuku-gyoemmae",
    unlocksRegionId: "shinjuku-gyoemmae",
    lines: ["marunouchi"],
  },
  {
    id: "station-shinjuku-sanchome",
    label: "Shinjuku-Sanchome",
    category: "station",
    emoji: "🚉",
    longitude: 139.705124,
    latitude: 35.691227,
    regionId: "shinjuku-sanchome",
    unlocksRegionId: "shinjuku-sanchome",
    lines: ["marunouchi"],
  },
  {
    id: "station-shirokane-takanawa",
    label: "Shirokane-Takanawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.73416,
    latitude: 35.64294,
    regionId: "shirokane-takanawa",
    unlocksRegionId: "shirokane-takanawa",
    lines: ["namboku"],
  },
  {
    id: "station-shirokanedai",
    label: "Shirokanedai",
    category: "station",
    emoji: "🚉",
    longitude: 139.726565,
    latitude: 35.638103,
    regionId: "shirokanedai",
    unlocksRegionId: "shirokanedai",
    lines: ["namboku"],
  },
  {
    id: "station-shonan-kaigan-koen",
    label: "Shonan-Kaigan-Koen",
    category: "station",
    emoji: "🚉",
    longitude: 139.486227,
    latitude: 35.315921,
    regionId: "shonan-kaigan-koen",
    unlocksRegionId: "shonan-kaigan-koen",
    lines: ["enoden"],
  },
  {
    id: "station-sobudaimae",
    label: "Sobudaimae",
    category: "station",
    emoji: "🚉",
    longitude: 139.421318,
    latitude: 35.518427,
    regionId: "sobudaimae",
    unlocksRegionId: "sobudaimae",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-soshigaya-okura",
    label: "Soshigaya-Okura",
    category: "station",
    emoji: "🚉",
    longitude: 139.610421,
    latitude: 35.638127,
    regionId: "soshigaya-okura",
    unlocksRegionId: "soshigaya-okura",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-suehirocho",
    label: "Suehirocho",
    category: "station",
    emoji: "🚉",
    longitude: 139.771524,
    latitude: 35.701932,
    regionId: "suehirocho",
    unlocksRegionId: "suehirocho",
    lines: ["ginza"],
  },
  {
    id: "station-sugamo",
    label: "Sugamo",
    category: "station",
    emoji: "🚉",
    longitude: 139.738823,
    latitude: 35.7336,
    regionId: "sugamo",
    unlocksRegionId: "sugamo",
    lines: ["yamanote"],
  },
  {
    id: "station-suzukakedai",
    label: "Suzukakedai",
    category: "station",
    emoji: "🚉",
    longitude: 139.481437,
    latitude: 35.516911,
    regionId: "suzukakedai",
    unlocksRegionId: "suzukakedai",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tabata",
    label: "Tabata",
    category: "station",
    emoji: "🚉",
    longitude: 139.761707,
    latitude: 35.737372,
    regionId: "tabata",
    unlocksRegionId: "tabata",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-tachikawa",
    label: "Tachikawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.413752,
    latitude: 35.698038,
    regionId: "tachikawa",
    unlocksRegionId: "tachikawa",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-takadanobaba",
    label: "Takadanobaba",
    category: "station",
    emoji: "🚉",
    longitude: 139.704179,
    latitude: 35.712902,
    regionId: "takadanobaba",
    unlocksRegionId: "takadanobaba",
    lines: ["yamanote"],
  },
  {
    id: "station-takanawa-gateway",
    label: "Takanawa Gateway",
    category: "station",
    emoji: "🚉",
    longitude: 139.740664,
    latitude: 35.635399,
    regionId: "takanawa-gateway",
    unlocksRegionId: "takanawa-gateway",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-takao",
    label: "Takao",
    category: "station",
    emoji: "🚉",
    longitude: 139.291517,
    latitude: 35.642527,
    regionId: "takao",
    unlocksRegionId: "takao",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-takatsu",
    label: "Takatsu",
    category: "station",
    emoji: "🚉",
    longitude: 139.616964,
    latitude: 35.603179,
    regionId: "takatsu",
    unlocksRegionId: "takatsu",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tama-plaza",
    label: "Tama-Plaza",
    category: "station",
    emoji: "🚉",
    longitude: 139.558874,
    latitude: 35.577527,
    regionId: "tama-plaza",
    unlocksRegionId: "tama-plaza",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tamachi",
    label: "Tamachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.747683,
    latitude: 35.645736,
    regionId: "tamachi",
    unlocksRegionId: "tamachi",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-tamagawagakuen-mae",
    label: "Tamagawagakuen-mae",
    category: "station",
    emoji: "🚉",
    longitude: 139.487421,
    latitude: 35.579624,
    regionId: "tamagawagakuen-mae",
    unlocksRegionId: "tamagawagakuen-mae",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-tameike-sanno",
    label: "Tameike-Sanno",
    category: "station",
    emoji: "🚉",
    longitude: 139.741692,
    latitude: 35.672262,
    regionId: "tameike-sanno",
    unlocksRegionId: "tameike-sanno",
    lines: ["namboku", "ginza"],
  },
  {
    id: "station-tana",
    label: "Tana",
    category: "station",
    emoji: "🚉",
    longitude: 139.504908,
    latitude: 35.536257,
    regionId: "tana",
    unlocksRegionId: "tana",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tawaramachi",
    label: "Tawaramachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.788412,
    latitude: 35.711614,
    regionId: "tawaramachi",
    unlocksRegionId: "tawaramachi",
    lines: ["ginza"],
  },
  {
    id: "station-toda",
    label: "Toda",
    category: "station",
    emoji: "🚉",
    longitude: 139.669597,
    latitude: 35.817699,
    regionId: "toda",
    unlocksRegionId: "toda",
    lines: ["saikyo"],
  },
  {
    id: "station-toda-koen",
    label: "Toda-Koen",
    category: "station",
    emoji: "🚉",
    longitude: 139.678195,
    latitude: 35.807909,
    regionId: "toda-koen",
    unlocksRegionId: "toda-koen",
    lines: ["saikyo"],
  },
  {
    id: "station-todaimae",
    label: "Todaimae",
    category: "station",
    emoji: "🚉",
    longitude: 139.758177,
    latitude: 35.717337,
    regionId: "todaimae",
    unlocksRegionId: "todaimae",
    lines: ["namboku"],
  },
  {
    id: "station-tokaidaigaku-mae",
    label: "Tokaidaigaku-mae",
    category: "station",
    emoji: "🚉",
    longitude: 139.281244,
    latitude: 35.379415,
    regionId: "tokaidaigaku-mae",
    unlocksRegionId: "tokaidaigaku-mae",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-tokyo",
    label: "Tokyo",
    category: "station",
    emoji: "🚉",
    longitude: 139.766441,
    latitude: 35.680611,
    regionId: "tokyo",
    unlocksRegionId: "tokyo",
    lines: ["yamanote", "keihin-tohoku", "chuo-rapid", "marunouchi"],
  },
  {
    id: "station-toranomon",
    label: "Toranomon",
    category: "station",
    emoji: "🚉",
    longitude: 139.750324,
    latitude: 35.667418,
    regionId: "toranomon",
    unlocksRegionId: "toranomon",
    lines: ["ginza"],
  },
  {
    id: "station-toyoda",
    label: "Toyoda",
    category: "station",
    emoji: "🚉",
    longitude: 139.383821,
    latitude: 35.663548,
    regionId: "toyoda",
    unlocksRegionId: "toyoda",
    lines: ["chuo-rapid"],
  },
  {
    id: "station-tsukimino",
    label: "Tsukimino",
    category: "station",
    emoji: "🚉",
    longitude: 139.458272,
    latitude: 35.51039,
    regionId: "tsukimino",
    unlocksRegionId: "tsukimino",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tsukushino",
    label: "Tsukushino",
    category: "station",
    emoji: "🚉",
    longitude: 139.48511,
    latitude: 35.527637,
    regionId: "tsukushino",
    unlocksRegionId: "tsukushino",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tsurumaki-onsen",
    label: "Tsurumaki-Onsen",
    category: "station",
    emoji: "🚉",
    longitude: 139.245417,
    latitude: 35.386218,
    regionId: "tsurumaki-onsen",
    unlocksRegionId: "tsurumaki-onsen",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-tsurukawa",
    label: "Tsurukawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.488924,
    latitude: 35.595718,
    regionId: "tsurukawa",
    unlocksRegionId: "tsurukawa",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-tsurumi",
    label: "Tsurumi",
    category: "station",
    emoji: "🚉",
    longitude: 139.675976,
    latitude: 35.508339,
    regionId: "tsurumi",
    unlocksRegionId: "tsurumi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-ueno",
    label: "Ueno",
    category: "station",
    emoji: "🚉",
    longitude: 139.776755,
    latitude: 35.712314,
    regionId: "ueno",
    unlocksRegionId: "ueno",
    lines: ["yamanote", "keihin-tohoku", "ginza"],
  },
  {
    id: "station-ueno-hirokoji",
    label: "Ueno-Hirokoji",
    category: "station",
    emoji: "🚉",
    longitude: 139.773821,
    latitude: 35.707914,
    regionId: "ueno-hirokoji",
    unlocksRegionId: "ueno-hirokoji",
    lines: ["ginza"],
  },
  {
    id: "station-uguisudani",
    label: "Uguisudani",
    category: "station",
    emoji: "🚉",
    longitude: 139.777917,
    latitude: 35.721703,
    regionId: "uguisudani",
    unlocksRegionId: "uguisudani",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-ukima-funado",
    label: "Ukima-Funado",
    category: "station",
    emoji: "🚉",
    longitude: 139.69151,
    latitude: 35.79118,
    regionId: "ukima-funado",
    unlocksRegionId: "ukima-funado",
    lines: ["saikyo"],
  },
  {
    id: "station-umegaoka",
    label: "Umegaoka",
    category: "station",
    emoji: "🚉",
    longitude: 139.652924,
    latitude: 35.656414,
    regionId: "umegaoka",
    unlocksRegionId: "umegaoka",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-urawa",
    label: "Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.657188,
    latitude: 35.858988,
    regionId: "urawa",
    unlocksRegionId: "urawa",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-wadazuka",
    label: "Wadazuka",
    category: "station",
    emoji: "🚉",
    longitude: 139.551814,
    latitude: 35.317814,
    regionId: "wadazuka",
    unlocksRegionId: "wadazuka",
    lines: ["enoden"],
  },
  {
    id: "station-warabi",
    label: "Warabi",
    category: "station",
    emoji: "🚉",
    longitude: 139.69038,
    latitude: 35.828123,
    regionId: "warabi",
    unlocksRegionId: "warabi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yamate",
    label: "Yamate",
    category: "station",
    emoji: "🚉",
    longitude: 139.646284,
    latitude: 35.427203,
    regionId: "yamate",
    unlocksRegionId: "yamate",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yanagikoji",
    label: "Yanagikoji",
    category: "station",
    emoji: "🚉",
    longitude: 139.489317,
    latitude: 35.324021,
    regionId: "yanagikoji",
    unlocksRegionId: "yanagikoji",
    lines: ["enoden"],
  },
  {
    id: "station-yoga",
    label: "Yoga",
    category: "station",
    emoji: "🚉",
    longitude: 139.634154,
    latitude: 35.626647,
    regionId: "yoga",
    unlocksRegionId: "yoga",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-yokodai",
    label: "Yokodai",
    category: "station",
    emoji: "🚉",
    longitude: 139.596465,
    latitude: 35.378698,
    regionId: "yokodai",
    unlocksRegionId: "yokodai",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yokohama",
    label: "Yokohama",
    category: "station",
    emoji: "🚉",
    longitude: 139.621649,
    latitude: 35.465566,
    regionId: "yokohama",
    unlocksRegionId: "yokohama",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yomiuriland-mae",
    label: "Yomiuriland-mae",
    category: "station",
    emoji: "🚉",
    longitude: 139.534728,
    latitude: 35.615117,
    regionId: "yomiuriland-mae",
    unlocksRegionId: "yomiuriland-mae",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-yono",
    label: "Yono",
    category: "station",
    emoji: "🚉",
    longitude: 139.639152,
    latitude: 35.884398,
    regionId: "yono",
    unlocksRegionId: "yono",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yono-honmachi",
    label: "Yono-Honmachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.62602,
    latitude: 35.881202,
    regionId: "yono-honmachi",
    unlocksRegionId: "yono-honmachi",
    lines: ["saikyo"],
  },
  {
    id: "station-yotsuya",
    label: "Yotsuya",
    category: "station",
    emoji: "🚉",
    longitude: 139.730014,
    latitude: 35.685541,
    regionId: "yotsuya",
    unlocksRegionId: "yotsuya",
    lines: ["namboku", "chuo-rapid", "marunouchi"],
  },
  {
    id: "station-yotsuya-sanchome",
    label: "Yotsuya-Sanchome",
    category: "station",
    emoji: "🚉",
    longitude: 139.722712,
    latitude: 35.686527,
    regionId: "yotsuya-sanchome",
    unlocksRegionId: "yotsuya-sanchome",
    lines: ["marunouchi"],
  },
  {
    id: "station-yoyogi",
    label: "Yoyogi",
    category: "station",
    emoji: "🚉",
    longitude: 139.701839,
    latitude: 35.68376,
    regionId: "yoyogi",
    unlocksRegionId: "yoyogi",
    lines: ["yamanote"],
  },
  {
    id: "station-yoyogi-hachiman",
    label: "Yoyogi-Hachiman",
    category: "station",
    emoji: "🚉",
    longitude: 139.688317,
    latitude: 35.671214,
    regionId: "yoyogi-hachiman",
    unlocksRegionId: "yoyogi-hachiman",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-yoyogi-uehara",
    label: "Yoyogi-Uehara",
    category: "station",
    emoji: "🚉",
    longitude: 139.683214,
    latitude: 35.668523,
    regionId: "yoyogi-uehara",
    unlocksRegionId: "yoyogi-uehara",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-yuigahama",
    label: "Yuigahama",
    category: "station",
    emoji: "🚉",
    longitude: 139.549321,
    latitude: 35.316814,
    regionId: "yuigahama",
    unlocksRegionId: "yuigahama",
    lines: ["enoden"],
  },
  {
    id: "station-yurakucho",
    label: "Yurakucho",
    category: "station",
    emoji: "🚉",
    longitude: 139.762592,
    latitude: 35.675464,
    regionId: "yurakucho",
    unlocksRegionId: "yurakucho",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-yurigaoka",
    label: "Yurigaoka",
    category: "station",
    emoji: "🚉",
    longitude: 139.516218,
    latitude: 35.611712,
    regionId: "yurigaoka",
    unlocksRegionId: "yurigaoka",
    lines: ["odakyu-odawara"],
  },
  {
    id: "station-zengyo",
    label: "Zengyo",
    category: "station",
    emoji: "🚉",
    longitude: 139.464721,
    latitude: 35.371521,
    regionId: "zengyo",
    unlocksRegionId: "zengyo",
    lines: ["odakyu-odawara"],
  },
] as const satisfies readonly StationPoi[];

export type StationId = (typeof STATION_POIS)[number]["id"];
