import type { StationPoi } from "@/config/game";

export const STATION_POIS: StationPoi[] = [
  {
    id: "station-akabane",
    label: "Akabane",
    category: "station",
    emoji: "🚉",
    longitude: 139.7208,
    latitude: 35.778139,
    regionId: "akabane",
    unlocksRegionId: "akabane",
    lines: ["saikyo", "keihin-tohoku"],
  },
  {
    id: "station-akabane-iwabuchi",
    label: "Akabane-Iwabuchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.7221,
    latitude: 35.783448,
    regionId: "akabane-iwabuchi",
    unlocksRegionId: "akabane-iwabuchi",
    lines: ["namboku"],
  },
  {
    id: "station-akihabara",
    label: "Akihabara",
    category: "station",
    emoji: "🚉",
    longitude: 139.774309,
    latitude: 35.698551,
    regionId: "akihabara",
    unlocksRegionId: "akihabara",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-aobadai",
    label: "Aobadai",
    category: "station",
    emoji: "🚉",
    longitude: 139.517231,
    latitude: 35.542878,
    regionId: "aobadai",
    unlocksRegionId: "aobadai",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-azabu-juban",
    label: "Azabu-Juban",
    category: "station",
    emoji: "🚉",
    longitude: 139.736656,
    latitude: 35.65584,
    regionId: "azabu-juban",
    unlocksRegionId: "azabu-juban",
    lines: ["namboku"],
  },
  {
    id: "station-azamino",
    label: "Azamino",
    category: "station",
    emoji: "🚉",
    longitude: 139.553521,
    latitude: 35.568362,
    regionId: "azamino",
    unlocksRegionId: "azamino",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-chuo-rinkan",
    label: "Chuo-Rinkan",
    category: "station",
    emoji: "🚉",
    longitude: 139.444356,
    latitude: 35.507551,
    regionId: "chuo-rinkan",
    unlocksRegionId: "chuo-rinkan",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-ebisu",
    label: "Ebisu",
    category: "station",
    emoji: "🚉",
    longitude: 139.709427,
    latitude: 35.646708,
    regionId: "ebisu",
    unlocksRegionId: "ebisu",
    lines: ["yamanote", "saikyo"],
  },
  {
    id: "station-eda",
    label: "Eda",
    category: "station",
    emoji: "🚉",
    longitude: 139.551454,
    latitude: 35.558575,
    regionId: "eda",
    unlocksRegionId: "eda",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-fujigaoka",
    label: "Fujigaoka",
    category: "station",
    emoji: "🚉",
    longitude: 139.527979,
    latitude: 35.543498,
    regionId: "fujigaoka",
    unlocksRegionId: "fujigaoka",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-futako-shinchi",
    label: "Futako-Shinchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.622446,
    latitude: 35.607197,
    regionId: "futako-shinchi",
    unlocksRegionId: "futako-shinchi",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-futako-tamagawa",
    label: "Futako-Tamagawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.6268,
    latitude: 35.61179,
    regionId: "futako-tamagawa",
    unlocksRegionId: "futako-tamagawa",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-gotanda",
    label: "Gotanda",
    category: "station",
    emoji: "🚉",
    longitude: 139.723995,
    latitude: 35.626161,
    regionId: "gotanda",
    unlocksRegionId: "gotanda",
    lines: ["yamanote"],
  },
  {
    id: "station-hamamatsucho",
    label: "Hamamatsucho",
    category: "station",
    emoji: "🚉",
    longitude: 139.757062,
    latitude: 35.655111,
    regionId: "hamamatsucho",
    unlocksRegionId: "hamamatsucho",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-harajuku",
    label: "Harajuku",
    category: "station",
    emoji: "🚉",
    longitude: 139.702427,
    latitude: 35.670215,
    regionId: "harajuku",
    unlocksRegionId: "harajuku",
    lines: ["yamanote"],
  },
  {
    id: "station-higashi-jujo",
    label: "Higashi-Jujo",
    category: "station",
    emoji: "🚉",
    longitude: 139.726875,
    latitude: 35.763848,
    regionId: "higashi-jujo",
    unlocksRegionId: "higashi-jujo",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-higashi-kanagawa",
    label: "Higashi-Kanagawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.633327,
    latitude: 35.477943,
    regionId: "higashi-kanagawa",
    unlocksRegionId: "higashi-kanagawa",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-hon-komagome",
    label: "Hon-Komagome",
    category: "station",
    emoji: "🚉",
    longitude: 139.753701,
    latitude: 35.724763,
    regionId: "hon-komagome",
    unlocksRegionId: "hon-komagome",
    lines: ["namboku"],
  },
  {
    id: "station-ichigao",
    label: "Ichigao",
    category: "station",
    emoji: "🚉",
    longitude: 139.541281,
    latitude: 35.551348,
    regionId: "ichigao",
    unlocksRegionId: "ichigao",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-ichigaya",
    label: "Ichigaya",
    category: "station",
    emoji: "🚉",
    longitude: 139.736659,
    latitude: 35.692079,
    regionId: "ichigaya",
    unlocksRegionId: "ichigaya",
    lines: ["namboku"],
  },
  {
    id: "station-iidabashi",
    label: "Iidabashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.744835,
    latitude: 35.701782,
    regionId: "iidabashi",
    unlocksRegionId: "iidabashi",
    lines: ["namboku"],
  },
  {
    id: "station-ikebukuro",
    label: "Ikebukuro",
    category: "station",
    emoji: "🚉",
    longitude: 139.710508,
    latitude: 35.729955,
    regionId: "ikebukuro",
    unlocksRegionId: "ikebukuro",
    lines: ["yamanote", "saikyo"],
  },
  {
    id: "station-ikejiri-ohashi",
    label: "Ikejiri-Ohashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.684772,
    latitude: 35.650763,
    regionId: "ikejiri-ohashi",
    unlocksRegionId: "ikejiri-ohashi",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-ishikawacho",
    label: "Ishikawacho",
    category: "station",
    emoji: "🚉",
    longitude: 139.642747,
    latitude: 35.439226,
    regionId: "ishikawacho",
    unlocksRegionId: "ishikawacho",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-isogo",
    label: "Isogo",
    category: "station",
    emoji: "🚉",
    longitude: 139.618158,
    latitude: 35.400137,
    regionId: "isogo",
    unlocksRegionId: "isogo",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-itabashi",
    label: "Itabashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.719437,
    latitude: 35.745272,
    regionId: "itabashi",
    unlocksRegionId: "itabashi",
    lines: ["saikyo"],
  },
  {
    id: "station-jujo",
    label: "Jujo",
    category: "station",
    emoji: "🚉",
    longitude: 139.722307,
    latitude: 35.760008,
    regionId: "jujo",
    unlocksRegionId: "jujo",
    lines: ["saikyo"],
  },
  {
    id: "station-kajigaya",
    label: "Kajigaya",
    category: "station",
    emoji: "🚉",
    longitude: 139.605479,
    latitude: 35.593651,
    regionId: "kajigaya",
    unlocksRegionId: "kajigaya",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-kamata",
    label: "Kamata",
    category: "station",
    emoji: "🚉",
    longitude: 139.715272,
    latitude: 35.561884,
    regionId: "kamata",
    unlocksRegionId: "kamata",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kami-nakazato",
    label: "Kami-Nakazato",
    category: "station",
    emoji: "🚉",
    longitude: 139.74698,
    latitude: 35.746579,
    regionId: "kami-nakazato",
    unlocksRegionId: "kami-nakazato",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kanda",
    label: "Kanda",
    category: "station",
    emoji: "🚉",
    longitude: 139.7709,
    latitude: 35.692754,
    regionId: "kanda",
    unlocksRegionId: "kanda",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-kannai",
    label: "Kannai",
    category: "station",
    emoji: "🚉",
    longitude: 139.63637,
    latitude: 35.444706,
    regionId: "kannai",
    unlocksRegionId: "kannai",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kawaguchi",
    label: "Kawaguchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.717512,
    latitude: 35.801926,
    regionId: "kawaguchi",
    unlocksRegionId: "kawaguchi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kawasaki",
    label: "Kawasaki",
    category: "station",
    emoji: "🚉",
    longitude: 139.696893,
    latitude: 35.531404,
    regionId: "kawasaki",
    unlocksRegionId: "kawasaki",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kita-akabane",
    label: "Kita-Akabane",
    category: "station",
    emoji: "🚉",
    longitude: 139.706029,
    latitude: 35.786781,
    regionId: "kita-akabane",
    unlocksRegionId: "kita-akabane",
    lines: ["saikyo"],
  },
  {
    id: "station-kita-toda",
    label: "Kita-Toda",
    category: "station",
    emoji: "🚉",
    longitude: 139.660111,
    latitude: 35.827653,
    regionId: "kita-toda",
    unlocksRegionId: "kita-toda",
    lines: ["saikyo"],
  },
  {
    id: "station-kita-urawa",
    label: "Kita-Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.646106,
    latitude: 35.872155,
    regionId: "kita-urawa",
    unlocksRegionId: "kita-urawa",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-kita-yono",
    label: "Kita-Yono",
    category: "station",
    emoji: "🚉",
    longitude: 139.628505,
    latitude: 35.890498,
    regionId: "kita-yono",
    unlocksRegionId: "kita-yono",
    lines: ["saikyo"],
  },
  {
    id: "station-komagome",
    label: "Komagome",
    category: "station",
    emoji: "🚉",
    longitude: 139.747001,
    latitude: 35.736286,
    regionId: "komagome",
    unlocksRegionId: "komagome",
    lines: ["yamanote", "namboku"],
  },
  {
    id: "station-komazawa-daigaku",
    label: "Komazawa-Daigaku",
    category: "station",
    emoji: "🚉",
    longitude: 139.661156,
    latitude: 35.633193,
    regionId: "komazawa-daigaku",
    unlocksRegionId: "komazawa-daigaku",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-konandai",
    label: "Konandai",
    category: "station",
    emoji: "🚉",
    longitude: 139.576696,
    latitude: 35.375295,
    regionId: "konandai",
    unlocksRegionId: "konandai",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-korakuen",
    label: "Korakuen",
    category: "station",
    emoji: "🚉",
    longitude: 139.751507,
    latitude: 35.707801,
    regionId: "korakuen",
    unlocksRegionId: "korakuen",
    lines: ["namboku"],
  },
  {
    id: "station-meguro",
    label: "Meguro",
    category: "station",
    emoji: "🚉",
    longitude: 139.715752,
    latitude: 35.633287,
    regionId: "meguro",
    unlocksRegionId: "meguro",
    lines: ["yamanote", "namboku"],
  },
  {
    id: "station-mejiro",
    label: "Mejiro",
    category: "station",
    emoji: "🚉",
    longitude: 139.706465,
    latitude: 35.721192,
    regionId: "mejiro",
    unlocksRegionId: "mejiro",
    lines: ["yamanote"],
  },
  {
    id: "station-minami-machida-grandberry-park",
    label: "Minami-Machida Grandberry Park",
    category: "station",
    emoji: "🚉",
    longitude: 139.470791,
    latitude: 35.511501,
    regionId: "minami-machida-grandberry-park",
    unlocksRegionId: "minami-machida-grandberry-park",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-minami-urawa",
    label: "Minami-Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.669144,
    latitude: 35.847732,
    regionId: "minami-urawa",
    unlocksRegionId: "minami-urawa",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-minami-yono",
    label: "Minami-Yono",
    category: "station",
    emoji: "🚉",
    longitude: 139.631039,
    latitude: 35.867886,
    regionId: "minami-yono",
    unlocksRegionId: "minami-yono",
    lines: ["saikyo"],
  },
  {
    id: "station-miyamaedaira",
    label: "Miyamaedaira",
    category: "station",
    emoji: "🚉",
    longitude: 139.582039,
    latitude: 35.584962,
    regionId: "miyamaedaira",
    unlocksRegionId: "miyamaedaira",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-miyazakidai",
    label: "Miyazakidai",
    category: "station",
    emoji: "🚉",
    longitude: 139.591125,
    latitude: 35.587053,
    regionId: "miyazakidai",
    unlocksRegionId: "miyazakidai",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-mizonokuchi",
    label: "Mizonokuchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.610511,
    latitude: 35.599925,
    regionId: "mizonokuchi",
    unlocksRegionId: "mizonokuchi",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-musashi-urawa",
    label: "Musashi-Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.647066,
    latitude: 35.845969,
    regionId: "musashi-urawa",
    unlocksRegionId: "musashi-urawa",
    lines: ["saikyo"],
  },
  {
    id: "station-nagatacho",
    label: "Nagatacho",
    category: "station",
    emoji: "🚉",
    longitude: 139.739896,
    latitude: 35.67832,
    regionId: "nagatacho",
    unlocksRegionId: "nagatacho",
    lines: ["namboku"],
  },
  {
    id: "station-nagatsuta",
    label: "Nagatsuta",
    category: "station",
    emoji: "🚉",
    longitude: 139.49437,
    latitude: 35.531899,
    regionId: "nagatsuta",
    unlocksRegionId: "nagatsuta",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-naka-urawa",
    label: "Naka-Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.637722,
    latitude: 35.853525,
    regionId: "naka-urawa",
    unlocksRegionId: "naka-urawa",
    lines: ["saikyo"],
  },
  {
    id: "station-negishi",
    label: "Negishi",
    category: "station",
    emoji: "🚉",
    longitude: 139.63505,
    latitude: 35.415657,
    regionId: "negishi",
    unlocksRegionId: "negishi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-nippori",
    label: "Nippori",
    category: "station",
    emoji: "🚉",
    longitude: 139.771001,
    latitude: 35.728483,
    regionId: "nippori",
    unlocksRegionId: "nippori",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-nishi-kawaguchi",
    label: "Nishi-Kawaguchi",
    category: "station",
    emoji: "🚉",
    longitude: 139.704482,
    latitude: 35.815583,
    regionId: "nishi-kawaguchi",
    unlocksRegionId: "nishi-kawaguchi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-nishi-nippori",
    label: "Nishi-Nippori",
    category: "station",
    emoji: "🚉",
    longitude: 139.767332,
    latitude: 35.73284,
    regionId: "nishi-nippori",
    unlocksRegionId: "nishi-nippori",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-nishigahara",
    label: "Nishigahara",
    category: "station",
    emoji: "🚉",
    longitude: 139.742172,
    latitude: 35.74605,
    regionId: "nishigahara",
    unlocksRegionId: "nishigahara",
    lines: ["namboku"],
  },
  {
    id: "station-ofuna",
    label: "Ofuna",
    category: "station",
    emoji: "🚉",
    longitude: 139.531394,
    latitude: 35.353348,
    regionId: "ofuna",
    unlocksRegionId: "ofuna",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-oimachi",
    label: "Oimachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.73454,
    latitude: 35.607159,
    regionId: "oimachi",
    unlocksRegionId: "oimachi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-oji",
    label: "Oji",
    category: "station",
    emoji: "🚉",
    longitude: 139.7379,
    latitude: 35.753154,
    regionId: "oji",
    unlocksRegionId: "oji",
    lines: ["keihin-tohoku", "namboku"],
  },
  {
    id: "station-oji-kamiya",
    label: "Oji-Kamiya",
    category: "station",
    emoji: "🚉",
    longitude: 139.735718,
    latitude: 35.765055,
    regionId: "oji-kamiya",
    unlocksRegionId: "oji-kamiya",
    lines: ["namboku"],
  },
  {
    id: "station-okachimachi",
    label: "Okachimachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.77463,
    latitude: 35.706953,
    regionId: "okachimachi",
    unlocksRegionId: "okachimachi",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-omiya",
    label: "Omiya",
    category: "station",
    emoji: "🚉",
    longitude: 139.62347,
    latitude: 35.907133,
    regionId: "omiya",
    unlocksRegionId: "omiya",
    lines: ["saikyo", "keihin-tohoku"],
  },
  {
    id: "station-omori",
    label: "Omori",
    category: "station",
    emoji: "🚉",
    longitude: 139.727933,
    latitude: 35.588473,
    regionId: "omori",
    unlocksRegionId: "omori",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-osaki",
    label: "Osaki",
    category: "station",
    emoji: "🚉",
    longitude: 139.728487,
    latitude: 35.61939,
    regionId: "osaki",
    unlocksRegionId: "osaki",
    lines: ["yamanote", "saikyo"],
  },
  {
    id: "station-otsuka",
    label: "Otsuka",
    category: "station",
    emoji: "🚉",
    longitude: 139.728588,
    latitude: 35.731685,
    regionId: "otsuka",
    unlocksRegionId: "otsuka",
    lines: ["yamanote"],
  },
  {
    id: "station-roppongi-itchome",
    label: "Roppongi-Itchome",
    category: "station",
    emoji: "🚉",
    longitude: 139.738849,
    latitude: 35.664973,
    regionId: "roppongi-itchome",
    unlocksRegionId: "roppongi-itchome",
    lines: ["namboku"],
  },
  {
    id: "station-saginuma",
    label: "Saginuma",
    category: "station",
    emoji: "🚉",
    longitude: 139.572855,
    latitude: 35.579444,
    regionId: "saginuma",
    unlocksRegionId: "saginuma",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-saitama-shintoshin",
    label: "Saitama-Shintoshin",
    category: "station",
    emoji: "🚉",
    longitude: 139.633948,
    latitude: 35.893637,
    regionId: "saitama-shintoshin",
    unlocksRegionId: "saitama-shintoshin",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-sakura-shinmachi",
    label: "Sakura-Shinmachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.645369,
    latitude: 35.631724,
    regionId: "sakura-shinmachi",
    unlocksRegionId: "sakura-shinmachi",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-sakuragicho",
    label: "Sakuragicho",
    category: "station",
    emoji: "🚉",
    longitude: 139.630894,
    latitude: 35.450316,
    regionId: "sakuragicho",
    unlocksRegionId: "sakuragicho",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-sangen-jaya",
    label: "Sangen-Jaya",
    category: "station",
    emoji: "🚉",
    longitude: 139.670186,
    latitude: 35.643806,
    regionId: "sangen-jaya",
    unlocksRegionId: "sangen-jaya",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-shibuya",
    label: "Shibuya",
    category: "station",
    emoji: "🚉",
    longitude: 139.701637,
    latitude: 35.658713,
    regionId: "shibuya",
    unlocksRegionId: "shibuya",
    lines: ["yamanote", "saikyo", "den-en-toshi"],
  },
  {
    id: "station-shimo",
    label: "Shimo",
    category: "station",
    emoji: "🚉",
    longitude: 139.732526,
    latitude: 35.777904,
    regionId: "shimo",
    unlocksRegionId: "shimo",
    lines: ["namboku"],
  },
  {
    id: "station-shin-koyasu",
    label: "Shin-Koyasu",
    category: "station",
    emoji: "🚉",
    longitude: 139.654164,
    latitude: 35.486875,
    regionId: "shin-koyasu",
    unlocksRegionId: "shin-koyasu",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-shin-okubo",
    label: "Shin-Okubo",
    category: "station",
    emoji: "🚉",
    longitude: 139.700242,
    latitude: 35.701301,
    regionId: "shin-okubo",
    unlocksRegionId: "shin-okubo",
    lines: ["yamanote"],
  },
  {
    id: "station-shin-sugita",
    label: "Shin-Sugita",
    category: "station",
    emoji: "🚉",
    longitude: 139.619992,
    latitude: 35.386278,
    regionId: "shin-sugita",
    unlocksRegionId: "shin-sugita",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-shinagawa",
    label: "Shinagawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.739068,
    latitude: 35.628449,
    regionId: "shinagawa",
    unlocksRegionId: "shinagawa",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-shinbashi",
    label: "Shinbashi",
    category: "station",
    emoji: "🚉",
    longitude: 139.75909,
    latitude: 35.666027,
    regionId: "shinbashi",
    unlocksRegionId: "shinbashi",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-shinjuku",
    label: "Shinjuku",
    category: "station",
    emoji: "🚉",
    longitude: 139.699785,
    latitude: 35.69033,
    regionId: "shinjuku",
    unlocksRegionId: "shinjuku",
    lines: ["yamanote", "saikyo"],
  },
  {
    id: "station-shirokane-takanawa",
    label: "Shirokane-Takanawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.73416,
    latitude: 35.64294,
    regionId: "shirokane-takanawa",
    unlocksRegionId: "shirokane-takanawa",
    lines: ["namboku"],
  },
  {
    id: "station-shirokanedai",
    label: "Shirokanedai",
    category: "station",
    emoji: "🚉",
    longitude: 139.726565,
    latitude: 35.638103,
    regionId: "shirokanedai",
    unlocksRegionId: "shirokanedai",
    lines: ["namboku"],
  },
  {
    id: "station-sugamo",
    label: "Sugamo",
    category: "station",
    emoji: "🚉",
    longitude: 139.738823,
    latitude: 35.7336,
    regionId: "sugamo",
    unlocksRegionId: "sugamo",
    lines: ["yamanote"],
  },
  {
    id: "station-suzukakedai",
    label: "Suzukakedai",
    category: "station",
    emoji: "🚉",
    longitude: 139.481437,
    latitude: 35.516911,
    regionId: "suzukakedai",
    unlocksRegionId: "suzukakedai",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tabata",
    label: "Tabata",
    category: "station",
    emoji: "🚉",
    longitude: 139.761707,
    latitude: 35.737372,
    regionId: "tabata",
    unlocksRegionId: "tabata",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-takadanobaba",
    label: "Takadanobaba",
    category: "station",
    emoji: "🚉",
    longitude: 139.704179,
    latitude: 35.712902,
    regionId: "takadanobaba",
    unlocksRegionId: "takadanobaba",
    lines: ["yamanote"],
  },
  {
    id: "station-takanawa-gateway",
    label: "Takanawa Gateway",
    category: "station",
    emoji: "🚉",
    longitude: 139.740664,
    latitude: 35.635399,
    regionId: "takanawa-gateway",
    unlocksRegionId: "takanawa-gateway",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-takatsu",
    label: "Takatsu",
    category: "station",
    emoji: "🚉",
    longitude: 139.616964,
    latitude: 35.603179,
    regionId: "takatsu",
    unlocksRegionId: "takatsu",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tama-plaza",
    label: "Tama-Plaza",
    category: "station",
    emoji: "🚉",
    longitude: 139.558874,
    latitude: 35.577527,
    regionId: "tama-plaza",
    unlocksRegionId: "tama-plaza",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tamachi",
    label: "Tamachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.747683,
    latitude: 35.645736,
    regionId: "tamachi",
    unlocksRegionId: "tamachi",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-tameike-sanno",
    label: "Tameike-Sanno",
    category: "station",
    emoji: "🚉",
    longitude: 139.741692,
    latitude: 35.672262,
    regionId: "tameike-sanno",
    unlocksRegionId: "tameike-sanno",
    lines: ["namboku"],
  },
  {
    id: "station-tana",
    label: "Tana",
    category: "station",
    emoji: "🚉",
    longitude: 139.504908,
    latitude: 35.536257,
    regionId: "tana",
    unlocksRegionId: "tana",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-toda",
    label: "Toda",
    category: "station",
    emoji: "🚉",
    longitude: 139.669597,
    latitude: 35.817699,
    regionId: "toda",
    unlocksRegionId: "toda",
    lines: ["saikyo"],
  },
  {
    id: "station-toda-koen",
    label: "Toda-Koen",
    category: "station",
    emoji: "🚉",
    longitude: 139.678195,
    latitude: 35.807909,
    regionId: "toda-koen",
    unlocksRegionId: "toda-koen",
    lines: ["saikyo"],
  },
  {
    id: "station-todaimae",
    label: "Todaimae",
    category: "station",
    emoji: "🚉",
    longitude: 139.758177,
    latitude: 35.717337,
    regionId: "todaimae",
    unlocksRegionId: "todaimae",
    lines: ["namboku"],
  },
  {
    id: "station-tokyo",
    label: "Tokyo",
    category: "station",
    emoji: "🚉",
    longitude: 139.766441,
    latitude: 35.680611,
    regionId: "tokyo",
    unlocksRegionId: "tokyo",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-tsukimino",
    label: "Tsukimino",
    category: "station",
    emoji: "🚉",
    longitude: 139.458272,
    latitude: 35.51039,
    regionId: "tsukimino",
    unlocksRegionId: "tsukimino",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tsukushino",
    label: "Tsukushino",
    category: "station",
    emoji: "🚉",
    longitude: 139.48511,
    latitude: 35.527637,
    regionId: "tsukushino",
    unlocksRegionId: "tsukushino",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-tsurumi",
    label: "Tsurumi",
    category: "station",
    emoji: "🚉",
    longitude: 139.675976,
    latitude: 35.508339,
    regionId: "tsurumi",
    unlocksRegionId: "tsurumi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-ueno",
    label: "Ueno",
    category: "station",
    emoji: "🚉",
    longitude: 139.776755,
    latitude: 35.712314,
    regionId: "ueno",
    unlocksRegionId: "ueno",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-uguisudani",
    label: "Uguisudani",
    category: "station",
    emoji: "🚉",
    longitude: 139.777917,
    latitude: 35.721703,
    regionId: "uguisudani",
    unlocksRegionId: "uguisudani",
    lines: ["yamanote", "keihin-tohoku"],
  },
  {
    id: "station-ukima-funado",
    label: "Ukima-Funado",
    category: "station",
    emoji: "🚉",
    longitude: 139.69151,
    latitude: 35.79118,
    regionId: "ukima-funado",
    unlocksRegionId: "ukima-funado",
    lines: ["saikyo"],
  },
  {
    id: "station-urawa",
    label: "Urawa",
    category: "station",
    emoji: "🚉",
    longitude: 139.657188,
    latitude: 35.858988,
    regionId: "urawa",
    unlocksRegionId: "urawa",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-warabi",
    label: "Warabi",
    category: "station",
    emoji: "🚉",
    longitude: 139.69038,
    latitude: 35.828123,
    regionId: "warabi",
    unlocksRegionId: "warabi",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yamate",
    label: "Yamate",
    category: "station",
    emoji: "🚉",
    longitude: 139.646284,
    latitude: 35.427203,
    regionId: "yamate",
    unlocksRegionId: "yamate",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yoga",
    label: "Yoga",
    category: "station",
    emoji: "🚉",
    longitude: 139.634154,
    latitude: 35.626647,
    regionId: "yoga",
    unlocksRegionId: "yoga",
    lines: ["den-en-toshi"],
  },
  {
    id: "station-yokodai",
    label: "Yokodai",
    category: "station",
    emoji: "🚉",
    longitude: 139.596465,
    latitude: 35.378698,
    regionId: "yokodai",
    unlocksRegionId: "yokodai",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yokohama",
    label: "Yokohama",
    category: "station",
    emoji: "🚉",
    longitude: 139.621649,
    latitude: 35.465566,
    regionId: "yokohama",
    unlocksRegionId: "yokohama",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yono",
    label: "Yono",
    category: "station",
    emoji: "🚉",
    longitude: 139.639152,
    latitude: 35.884398,
    regionId: "yono",
    unlocksRegionId: "yono",
    lines: ["keihin-tohoku"],
  },
  {
    id: "station-yono-honmachi",
    label: "Yono-Honmachi",
    category: "station",
    emoji: "🚉",
    longitude: 139.62602,
    latitude: 35.881202,
    regionId: "yono-honmachi",
    unlocksRegionId: "yono-honmachi",
    lines: ["saikyo"],
  },
  {
    id: "station-yotsuya",
    label: "Yotsuya",
    category: "station",
    emoji: "🚉",
    longitude: 139.730014,
    latitude: 35.685541,
    regionId: "yotsuya",
    unlocksRegionId: "yotsuya",
    lines: ["namboku"],
  },
  {
    id: "station-yoyogi",
    label: "Yoyogi",
    category: "station",
    emoji: "🚉",
    longitude: 139.701839,
    latitude: 35.68376,
    regionId: "yoyogi",
    unlocksRegionId: "yoyogi",
    lines: ["yamanote"],
  },
  {
    id: "station-yurakucho",
    label: "Yurakucho",
    category: "station",
    emoji: "🚉",
    longitude: 139.762592,
    latitude: 35.675464,
    regionId: "yurakucho",
    unlocksRegionId: "yurakucho",
    lines: ["yamanote", "keihin-tohoku"],
  },
];
